CREATE DATABASE projeto_final;
USE projeto_final;
CREATE TABLE capas (num int(10) AUTO_INCREMENT NOT NULL primary key, referencia VARCHAR(300), materia VARCHAR(30));
CREATE TABLE hqs (num int(10) AUTO_INCREMENT NOT NULL primary key, referencia VARCHAR(300), nome VARCHAR(60), materia VARCHAR(30));
ALTER DATABASE projeto_final CHARSET = UTF8 COLLATE = utf8_general_ci;

INSERT INTO capas(referencia,materia) VALUES ('../dados/Capas/03.jpg','História');
INSERT INTO capas(referencia,materia) VALUES ('../dados/Capas/03.jpg','História');
INSERT INTO capas(referencia,materia) VALUES ('../dados/Capas/02.jpg','História');
INSERT INTO capas(referencia,materia) VALUES ('../dados/Capas/04.jpg','História');
INSERT INTO capas(referencia,materia) VALUES ('../dados/Capas/04.jpg','História');
INSERT INTO capas(referencia,materia) VALUES ('../dados/Capas/05.jpg','História');
INSERT INTO capas(referencia,materia) VALUES ('../dados/Capas/05.jpg','História');
INSERT INTO capas(referencia,materia) VALUES ('../dados/Capas/06.jpg','História');
INSERT INTO capas(referencia,materia) VALUES ('../dados/Capas/22.jpg','História');
INSERT INTO capas(referencia,materia) VALUES ('../dados/Capas/23.jpg','História');
INSERT INTO capas(referencia,materia) VALUES ('../dados/Capas/21.jpg','História');
INSERT INTO capas(referencia,materia) VALUES ('../dados/Capas/16.jpg','História');
INSERT INTO capas(referencia,materia) VALUES ('../dados/Capas/17.jpg','História');
INSERT INTO capas(referencia,materia) VALUES ('../dados/Capas/18.jpg','História');
INSERT INTO capas(referencia,materia) VALUES ('../dados/Capas/19.jpg','História');
INSERT INTO capas(referencia,materia) VALUES ('../dados/Capas/20.jpg','História');
INSERT INTO capas(referencia,materia) VALUES ('../dados/Capas/24.jpg','História');
INSERT INTO capas(referencia,materia) VALUES ('../dados/Capas/25.jpg','História');
INSERT INTO capas(referencia,materia) VALUES ('../dados/Capas/26.jpg','História');
INSERT INTO capas(referencia,materia) VALUES ('../dados/Capas/27.jpg','História');
INSERT INTO capas(referencia,materia) VALUES ('../dados/Capas/36.jpg','História');
INSERT INTO capas(referencia,materia) VALUES ('../dados/Capas/28.jpg','História');
INSERT INTO capas(referencia,materia) VALUES ('../dados/Capas/03.jpg','Física');
INSERT INTO capas(referencia,materia) VALUES ('../dados/Capas/03.jpg','Física');
INSERT INTO capas(referencia,materia) VALUES ('../dados/Capas/02.jpg','Física');
INSERT INTO capas(referencia,materia) VALUES ('../dados/Capas/08.jpg','Física');
INSERT INTO capas(referencia,materia) VALUES ('../dados/Capas/09.jpg','Física');
INSERT INTO capas(referencia,materia) VALUES ('../dados/Capas/10.jpg','Física');
INSERT INTO capas(referencia,materia) VALUES ('../dados/Capas/11.jpg','Física');
INSERT INTO capas(referencia,materia) VALUES ('../dados/Capas/12.jpg','Física');
INSERT INTO capas(referencia,materia) VALUES ('../dados/Capas/14.jpg','Física');
INSERT INTO capas(referencia,materia) VALUES ('../dados/Capas/02.jpg','Biologia');
INSERT INTO capas(referencia,materia) VALUES ('../dados/Capas/05.jpg','Biologia');
INSERT INTO capas(referencia,materia) VALUES ('../dados/Capas/05.jpg','Biologia');
INSERT INTO capas(referencia,materia) VALUES ('../dados/Capas/06.jpg','Biologia');
INSERT INTO capas(referencia,materia) VALUES ('../dados/Capas/06.jpg','Biologia');
INSERT INTO capas(referencia,materia) VALUES ('../dados/Capas/06.jpg','Biologia');
INSERT INTO capas(referencia,materia) VALUES ('../dados/Capas/06.jpg','Biologia');
INSERT INTO capas(referencia,materia) VALUES ('../dados/Capas/07.jpg','Biologia');
INSERT INTO capas(referencia,materia) VALUES ('../dados/Capas/07.jpg','Biologia');
INSERT INTO capas(referencia,materia) VALUES ('../dados/Capas/31.jpg','Biologia');
INSERT INTO capas(referencia,materia) VALUES ('../dados/Capas/34.jpg','Biologia');
INSERT INTO capas(referencia,materia) VALUES ('../dados/Capas/03.jpg','Química');
INSERT INTO capas(referencia,materia) VALUES ('../dados/Capas/02.jpg','Química');
INSERT INTO capas(referencia,materia) VALUES ('../dados/Capas/02.jpg','Química');
INSERT INTO capas(referencia,materia) VALUES ('../dados/Capas/02.jpg','Química');
INSERT INTO capas(referencia,materia) VALUES ('../dados/Capas/04.jpg','Química');
INSERT INTO capas(referencia,materia) VALUES ('../dados/Capas/05.jpg','Química');
INSERT INTO capas(referencia,materia) VALUES ('../dados/Capas/35.jpg','Química');

select * from capas;

INSERT INTO hqs(referencia,nome,materia) VALUES ('../dados/HQs/1.pdf','História do Barômetro','História');
INSERT INTO hqs(referencia,nome,materia) VALUES ('../dados/HQs/2.pdf','História do Vácuo','História');
INSERT INTO hqs(referencia,nome,materia) VALUES ('../dados/HQs/3.pdf','História da Força Hidráulica','História');
INSERT INTO hqs(referencia,nome,materia) VALUES ('../dados/HQs/4.pdf','Homem sob as Águas','História');
INSERT INTO hqs(referencia,nome,materia) VALUES ('../dados/HQs/5.pdf','Arquimedes e a Coroa do Rei','História');
INSERT INTO hqs(referencia,nome,materia) VALUES ('../dados/HQs/6.pdf','História das Vitaminas','História');
INSERT INTO hqs(referencia,nome,materia) VALUES ('../dados/HQs/7.pdf','História do Dr. Beaumont','História');
INSERT INTO hqs(referencia,nome,materia) VALUES ('../dados/HQs/8.pdf','História da Vacinação','História');
INSERT INTO hqs(referencia,nome,materia) VALUES ('../dados/HQs/9.pdf','História do Vidro','História');
INSERT INTO hqs(referencia,nome,materia) VALUES ('../dados/HQs/10.pdf','História do Papel','História');
INSERT INTO hqs(referencia,nome,materia) VALUES ('../dados/HQs/11.pdf','História da Televisão','História');
INSERT INTO hqs(referencia,nome,materia) VALUES ('../dados/HQs/12.pdf','História da Civilização I','História');
INSERT INTO hqs(referencia,nome,materia) VALUES ('../dados/HQs/13.pdf','História da Civilização II','História');
INSERT INTO hqs(referencia,nome,materia) VALUES ('../dados/HQs/14.pdf','História da Civilização III','História');
INSERT INTO hqs(referencia,nome,materia) VALUES ('../dados/HQs/15.pdf','História da Civilização IV','História');
INSERT INTO hqs(referencia,nome,materia) VALUES ('../dados/HQs/16.pdf','História da Civilização V','História');
INSERT INTO hqs(referencia,nome,materia) VALUES ('../dados/HQs/17.pdf','História da Civilização VI','História');
INSERT INTO hqs(referencia,nome,materia) VALUES ('../dados/HQs/18.pdf','História da Civilização VII','História');
INSERT INTO hqs(referencia,nome,materia) VALUES ('../dados/HQs/19.pdf','História da Civilização VIII','História');
INSERT INTO hqs(referencia,nome,materia) VALUES ('../dados/HQs/20.pdf','História da Civilização IX','História');
INSERT INTO hqs(referencia,nome,materia) VALUES ('../dados/HQs/21.pdf','História da Civilização X','História');
INSERT INTO hqs(referencia,nome,materia) VALUES ('../dados/HQs/30.pdf','História da Civilização XI','História');
INSERT INTO hqs(referencia,nome,materia) VALUES ('../dados/HQs/31.pdf','Peso da Atmosfera','Física');
INSERT INTO hqs(referencia,nome,materia) VALUES ('../dados/HQs/2.pdf','Fazer Trabalhar o Vácuo','Física');
INSERT INTO hqs(referencia,nome,materia) VALUES ('../dados/HQs/3.pdf','História da Força Hidráulica','Física');
INSERT INTO hqs(referencia,nome,materia) VALUES ('../dados/HQs/22.pdf','Romance da Eletricidade I','Física');
INSERT INTO hqs(referencia,nome,materia) VALUES ('../dados/HQs/23.pdf','Romance da Eletricidade II','Física');
INSERT INTO hqs(referencia,nome,materia) VALUES ('../dados/HQs/24.pdf','Romance da Eletricidade III','Física');
INSERT INTO hqs(referencia,nome,materia) VALUES ('../dados/HQs/25.pdf','Romance da Eletricidade IV','Física');
INSERT INTO hqs(referencia,nome,materia) VALUES ('../dados/HQs/26.pdf','História dos Raios X','Física');
INSERT INTO hqs(referencia,nome,materia) VALUES ('../dados/HQs/27.pdf','Do Ovo ao Raio X','Física');
INSERT INTO hqs(referencia,nome,materia) VALUES ('../dados/HQs/28.pdf','De Oceano a Oceano','Biologia');
INSERT INTO hqs(referencia,nome,materia) VALUES ('../dados/HQs/29.pdf','Combustível para a Máquina','Biologia');
INSERT INTO hqs(referencia,nome,materia) VALUES ('../dados/HQs/32.pdf','Saúde pela Alimentação','Biologia');
INSERT INTO hqs(referencia,nome,materia) VALUES ('../dados/HQs/33.pdf','O Trabalho do Sangue','Biologia');
INSERT INTO hqs(referencia,nome,materia) VALUES ('../dados/HQs/34.pdf','O Inimigo Invísivel do Homem','Biologia');
INSERT INTO hqs(referencia,nome,materia) VALUES ('../dados/HQs/35.pdf','A luta contra as bactérias','Biologia');
INSERT INTO hqs(referencia,nome,materia) VALUES ('../dados/HQs/36.pdf','Combatendo Germes com Germes','Biologia');
INSERT INTO hqs(referencia,nome,materia) VALUES ('../dados/HQs/37.pdf','Magia da Medicina Moderna','Biologia');
INSERT INTO hqs(referencia,nome,materia) VALUES ('../dados/HQs/38.pdf','Sono que Salava Vidas','Biologia');
INSERT INTO hqs(referencia,nome,materia) VALUES ('../dados/HQs/39.pdf','O Mundo Animal I','Biologia');
INSERT INTO hqs(referencia,nome,materia) VALUES ('../dados/HQs/40.pdf','O Mundo Animal II','Biologia');
INSERT INTO hqs(referencia,nome,materia) VALUES ('../dados/HQs/1.pdf','O Oceano de Ar','Química');
INSERT INTO hqs(referencia,nome,materia) VALUES ('../dados/HQs/41.pdf','Causas da Combustão','Química');
INSERT INTO hqs(referencia,nome,materia) VALUES ('../dados/HQs/42.pdf','Mistério e Domínio do Fogo','Química');
INSERT INTO hqs(referencia,nome,materia) VALUES ('../dados/HQs/43.pdf','Outras Partes da Atmosfera','Química');
INSERT INTO hqs(referencia,nome,materia) VALUES ('../dados/HQs/44.pdf','Rendimento da Água','Química');
INSERT INTO hqs(referencia,nome,materia) VALUES ('../dados/HQs/45.pdf','O Laboratório Químico do Organismo','Química');
INSERT INTO hqs(referencia,nome,materia) VALUES ('../dados/HQs/46.pdf','Aventuras no Coração do Átomo','Química');

select * from hqs;